### ISSUE TITLE
Normalizing the context for cross-attention

### ISSUE THREAD

**Issue by yoavhacohen** [lucidrains/recurrent-interface-network-pytorch#17]
This implementation normalizes the context for cross attention ([here](https://github.com/lucidrains/recurrent-interface-network-pytorch/blob/9704aed62aae4299df5128bffb1fcadde6650c40/rin_pytorch/rin_pytorch.py#L294) and [here](https://github.com/lucidrains/recurrent-interface-network-pytorch/blob/9704aed62aae4299df5128bffb1fcadde6650c40/rin_pytorch/rin_pytorch.py#L310)).

However, the pseudo code in the paper ("Algorithm 3") does not normalize the context.

Any insight on this?

**Comment by lucidrains** [comment]
@yoavhacohen in the original transformer, you cross attend to the normalized tokens from the encoder

it is just standard practice

**Comment by lucidrains** [comment]
@yoavhacohen if you run experiments and see better results without that norm, do let me know. that would be interesting
