### ISSUE TITLE
scale during sampling

### ISSUE THREAD

**Issue by zhangdan8962** [lucidrains/recurrent-interface-network-pytorch#19]
Hi,

Thank you so much for bringing the idea from [Chen's paper](https://arxiv.org/abs/2301.10972) into RIN.

In Algo 3 from Chen's paper, they did not mention 'scale' back the image during sampling. So I am wondering if we really need to do that in DDPM/DDIM sampler?

**Comment by lucidrains** [comment]
@zhangdan8962 oh! yes, i think you are correct, thank you

made the change

have you tried training RIN with Chen's scaling?

**Comment by zhangdan8962** [comment]
@lucidrains No, I did not have a chance yet.

I was trying to confirm the scaling operation during inference with Chen, but it says his email address not exists. I may have to check the pix2seq code for the answer.

**Comment by lucidrains** [comment]
@zhangdan8962 sg, you should just run it and share your results here. that would benefit everyone
