### ISSUE TITLE
Lacks a `ff` layer?

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/recurrent-interface-network-pytorch#3]
Hi Phil!
Compared to Algorithm3 Line 4, I found a little inconsistent,
![image](https://user-images.githubusercontent.com/39040787/215320254-bd4cc3a6-5e3b-4850-a8e2-828740620d24.png)

https://github.com/lucidrains/recurrent-interface-network-pytorch/blob/19862012f9f685d7a9dd6c2f88609b34f015dbf2/rin_pytorch/rin_pytorch.py#L310

maybe need 
```python
latents = self.latents_attend_to_patches(latents, patches, time = t) + latents 
latents = self.latents_cross_attn_ff(latents, time=t) + latents
```
just curious 😁

**Comment by lucidrains** [comment]
@CiaoHe Hi He Cao! Yes indeed all attention should be followed by feedforwards, thank you for catching this!
