### ISSUE TITLE
Potential Issue with Self-Conditioning

### ISSUE THREAD

**Issue by justinlovelace** [lucidrains/recurrent-interface-network-pytorch#8]
Hello Phil! Thank you for all of your excellent open-source implementations!

I noticed a potential bug with self-conditioning in pixel-space. If the model is trained to predict eps instead of x_0, then I think the model is currently being conditioned on the predicted epsilon instead of the predicted image. 

I shared the relevant snippet of code below. It looks like it's conditioned on the output of the network regardless of whether it's being trained to predict x_0 or eps.

My apologies if I'm misunderstanding something!

<img width="927" alt="image" src="https://user-images.githubusercontent.com/22563227/222823973-72e3e1fe-bd2f-44cf-ab43-f89137847bb7.png">

**Comment by lucidrains** [comment]
@justinlovelace oh yes :facepalm: 

i added the epsilon objective at some point but forgot to account for that

thank you Justin! can you see if [this commit](https://github.com/lucidrains/recurrent-interface-network-pytorch/commit/862b0046e15bc87f309b7d6098411b503d4e0e69#diff-c245517a15c6c34e71df6f08ed422324484176189f4795463b7e58278d35b9cdR750) looks good?

**Comment by justinlovelace** [comment]
Looks good to me! Appreciate the quick response!
